export type ToolKind = 'date-after' | 'date-before' | 'date-difference' | 'video-speed' | 'discount' | 'percentage' | 'unit-price' | 'hourly-monthly' | 'character-count' | 'random-picker' | 'roulette' | 'image-converter' | 'image-crop' | 'qr-code' | 'password-generator' | 'image-resize' | 'text-replace' | 'csv-tsv-converter';

export interface ToolDefinition {
  slug: string; title: string; shortTitle: string; purpose: string; description: string; inputs: string[]; outputs: string[]; example: string; category: string; keywords: string[]; relatedTools: string[]; status: 'draft' | 'published'; kind: ToolKind;
}

export const tools: ToolDefinition[] = [
  {slug:'date-after', title:'日付±日数', shortTitle:'日付±日数', purpose:'基準日から前後の日付を知る', description:'基準日から日数・週数・月数・年数を足し引きして日付を計算します。', inputs:['基準日','数値','方向','単位'], outputs:['計算後の日付'], example:'今日から30日後 → 計算結果', category:'日付', keywords:['日付','日数','計算'], relatedTools:['date-difference'], status:'published', kind:'date-after'},
  {slug:'date-difference', title:'2つの日付の差', shortTitle:'日付の差', purpose:'2つの日付の間の日数を知る', description:'2つの日付の間が何日あるかを計算します。', inputs:['開始日','終了日'], outputs:['2つの日付の差（日）'], example:'8月1日から8月31日 → 30日', category:'日付', keywords:['日付','日数','差'], relatedTools:['date-after'], status:'published', kind:'date-difference'},
  {slug:'video-speed', title:'動画を倍速で見ると何分？', shortTitle:'動画倍速再生時間', purpose:'倍速再生時の動画視聴時間を知る', description:'動画を倍速再生したときの、実際にかかる時間を計算します。', inputs:['動画時間（分）','再生速度'], outputs:['実際の再生時間'], example:'90分を1.5倍速 → 60分', category:'時間', keywords:['動画','倍速','再生時間'], relatedTools:['hourly-monthly'], status:'published', kind:'video-speed'},
  {slug:'discount', title:'割引計算', shortTitle:'割引計算', purpose:'割引後の支払額と値引き額を知る', description:'元の価格と割引率から、支払額と値引き額を計算します。', inputs:['元の価格','割引率'], outputs:['支払額','値引き額'], example:'1000円を20%引き → 800円', category:'お金', keywords:['割引','セール','価格'], relatedTools:['percentage','unit-price'], status:'published', kind:'discount'},
  {slug:'percentage', title:'パーセント計算', shortTitle:'パーセント計算', purpose:'ある数の指定割合を知る', description:'数値の何パーセントがいくらかを計算します。', inputs:['元の数','割合'], outputs:['該当する数値'], example:'1200の15% → 180', category:'お金', keywords:['パーセント','割合','%'], relatedTools:['discount','unit-price'], status:'published', kind:'percentage'},
  {slug:'unit-price', title:'どっちがお得？単価比較', shortTitle:'単価比較', purpose:'2商品の単位あたり価格を比べる', description:'2つの商品を同じ単位で比べて、安い方を確認します。', inputs:['商品Aの価格・内容量','商品Bの価格・内容量'], outputs:['各商品の単価','安い商品'], example:'同じ単位にそろえてAとBを比較', category:'お金', keywords:['単価','比較','お得'], relatedTools:['discount','percentage'], status:'published', kind:'unit-price'},
  {slug:'hourly-monthly', title:'時給から月収', shortTitle:'時給から月収', purpose:'働き方から収入の目安を知る', description:'時給と勤務日数から、週収・月収・年収の目安を計算します。', inputs:['時給','1日の勤務時間','週の勤務日数'], outputs:['週収','月収','年収'], example:'時給1200円・1日8時間・週5日で計算', category:'仕事', keywords:['時給','月収','年収'], relatedTools:['percentage','video-speed'], status:'published', kind:'hourly-monthly'},
  {slug:'character-count', title:'文字数カウント', shortTitle:'文字数カウント', purpose:'文章の長さをすぐ確認する', description:'文章の文字数、空白を除いた文字数、行数を数えます。', inputs:['文章'], outputs:['文字数','空白除外文字数','行数'], example:'文章を貼り付けるとリアルタイム集計', category:'文章', keywords:['文字数','文章','カウント'], relatedTools:['random-picker'], status:'published', kind:'character-count'},
  {slug:'random-picker', title:'ランダム抽選', shortTitle:'ランダム抽選', purpose:'複数の候補から1つを公平に選ぶ', description:'候補を1行ずつ入力すると、ランダムに1つ選びます。', inputs:['候補（1行1つ）'], outputs:['選ばれた候補'], example:'りんご\nみかん\nぶどう → 1つを抽選', category:'便利', keywords:['抽選','ランダム','くじ'], relatedTools:['character-count'], status:'published', kind:'random-picker'},
  {slug:'roulette', title:'ルーレット抽選', shortTitle:'ルーレット', purpose:'候補をルーレットで楽しく1つ選ぶ', description:'候補を1行ずつ入力して回すと、ランダムに1つを選びます。', inputs:['候補（1行1つ）'], outputs:['選ばれた候補'], example:'担当者や順番をルーレットで決める', category:'便利', keywords:['ルーレット','抽選','ランダム'], relatedTools:['random-picker'], status:'published', kind:'roulette'},
  {slug:'image-converter', title:'画像ファイル形式変換', shortTitle:'画像形式変換', purpose:'画像を使いたい形式へ変換する', description:'画像をPNG・JPG・WebPなどへ変換し、必要ならサイズと品質も調整できます。', inputs:['画像ファイル','出力形式','品質・サイズ'], outputs:['変換後の画像ファイル'], example:'PNG画像をWebPへ変換', category:'画像', keywords:['画像','形式','変換'], relatedTools:[], status:'published', kind:'image-converter'},
  {slug:'image-crop', title:'画像トリミング', shortTitle:'画像トリミング', purpose:'画像の必要な部分だけを切り抜く', description:'画像上をドラッグして範囲を選び、必要な部分だけを切り抜いて保存できます。', inputs:['画像ファイル','切り抜き範囲'], outputs:['トリミング後の画像ファイル'], example:'画像の一部分だけを切り抜く', category:'画像', keywords:['画像','トリミング','切り抜き'], relatedTools:['image-converter'], status:'published', kind:'image-crop'},
  {slug:'qr-code', title:'QRコード生成', shortTitle:'QRコード生成', purpose:'URLや短文をQRコード画像にする', description:'URLや短い文章を入力すると、QRコードを作成して保存できます。', inputs:['URL・短文'], outputs:['QRコード画像'], example:'URLを入力してQRコードを保存', category:'変換', keywords:['QR','コード','生成'], relatedTools:[], status:'published', kind:'qr-code'},
  {slug:'password-generator', title:'パスワード生成', shortTitle:'パスワード生成', purpose:'安全なパスワードをすぐ作る', description:'長さや大文字・数字・記号の有無を選んで、ランダムなパスワードを生成できます。', inputs:['長さ','文字種'], outputs:['パスワード'], example:'16文字・大文字あり・記号なし', category:'便利', keywords:['パスワード','生成','ランダム'], relatedTools:['random-picker'], status:'published', kind:'password-generator'},
  {slug:'image-resize', title:'画像リサイズ', shortTitle:'画像リサイズ', purpose:'画像の幅や高さを変更する', description:'画像を選び、幅または高さを指定してサイズを変更できます。', inputs:['画像ファイル','幅','高さ'], outputs:['リサイズ画像'], example:'画像の幅を1200pxにする', category:'画像', keywords:['画像','サイズ','リサイズ'], relatedTools:['image-converter','image-crop'], status:'published', kind:'image-resize'},
  {slug:'text-replace', title:'文字列一括置換', shortTitle:'文字列置換', purpose:'文章内の語句をまとめて置き換える', description:'文章と検索語・置換語を入力すると、変更後の文章をすぐ確認できます。', inputs:['文章','検索語','置換語'], outputs:['置換後の文章'], example:'古い商品名を新しい商品名へ置換', category:'文章', keywords:['文字列','置換','文章'], relatedTools:['character-count'], status:'published', kind:'text-replace'},
  {slug:'csv-tsv-converter', title:'CSV・TSV変換', shortTitle:'CSV・TSV変換', purpose:'CSVとTSVの区切り形式を相互変換する', description:'表形式のテキストを貼り付け、CSVまたはTSVへ変換してコピーできます。', inputs:['表形式テキスト','変換先'], outputs:['変換済みテキスト'], example:'CSVをTSVへ変換', category:'変換', keywords:['CSV','TSV','変換'], relatedTools:['text-replace'], status:'published', kind:'csv-tsv-converter'},
];

export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);
